### PR TITLE
Unified node model

### PR DESCRIPTION
**Pull request by s-l-teichmann**
With this PR the parser generates an unified node tree to simplify and speed up the evaluations.

### CODE REVIEW

**Comment by toirl** [comment]
@s-l-teichmann thanks for your improvement here. Unfortunately I don't find the time to look into it further yet. I like ot understand your changes in details before merging. Maybe we can talk about it this week?

**Comment by s-l-teichmann** [comment]
Just come over to my office.

**Comment by toirl** [comment]
Thanks for your contribution. PR merged and closed.

**Comment by s-l-teichmann** [comment]
Was this really merged? I only the the closing.

**Pull request merged**
